const mongoose=require('mongoose');const Cash=require('../models/CashRegister');const Sale=require('../models/Sale');const Product=require('../models/Product');
const METODOS=['EFECTIVO','TRANSFERENCIA','TARJETA'];
const historial=async(req,res)=>{const filtro=req.usuario.rol==='CAJERO'?{cajero:req.usuario._id}:{};res.json({ventas:await Sale.find(filtro).populate('cajero','nombre').sort({createdAt:-1}).limit(100)});};
const actual=async(req,res)=>res.json({caja:await Cash.findOne({cajero:req.usuario._id,estado:'ABIERTA'})});
const abrir=async(req,res)=>{const monto=Number(req.body.montoInicial);if(!Number.isFinite(monto)||monto<0)return res.status(400).json({mensaje:'Monto inicial inválido'});if(await Cash.exists({cajero:req.usuario._id,estado:'ABIERTA'}))return res.status(400).json({mensaje:'Ya tienes una caja abierta'});res.status(201).json({mensaje:'Caja abierta',caja:await Cash.create({cajero:req.usuario._id,montoInicial:monto})});};
const cerrar=async(req,res)=>{const monto=Number(req.body.montoFinal);if(!Number.isFinite(monto)||monto<0)return res.status(400).json({mensaje:'Monto final inválido'});const caja=await Cash.findOneAndUpdate({cajero:req.usuario._id,estado:'ABIERTA'},{$set:{estado:'CERRADA',montoFinal:monto,fechaCierre:new Date(),observacion:req.body.observacion||''}},{new:true});if(!caja)return res.status(400).json({mensaje:'No hay caja abierta'});const efectivoEsperado=caja.montoInicial+(caja.totalesPago?.EFECTIVO||0);res.json({mensaje:'Caja cerrada',caja,efectivoEsperado,diferencia:monto-efectivoEsperado});};
const vender=async(req,res)=>{const session=await mongoose.startSession();try{let venta;await session.withTransaction(async()=>{const caja=await Cash.findOne({cajero:req.usuario._id,estado:'ABIERTA'}).session(session);if(!caja)throw new Error('CAJA');if(!METODOS.includes(req.body.metodoPago))throw new Error('PAGO');if(!Array.isArray(req.body.items)||!req.body.items.length)throw new Error('ITEMS');const detalles=[];for(const i of req.body.items){const cantidad=Number(i.cantidad);if(!mongoose.isValidObjectId(i.producto)||!Number.isFinite(cantidad)||cantidad<=0)throw new Error('ITEMS');const p=await Product.findOneAndUpdate({_id:i.producto,estado:true,tipoProducto:{$in:['PRODUCTO_TERMINADO','REVENTA']},cantidadActual:{$gte:cantidad}},{$inc:{cantidadActual:-cantidad}},{new:true,session});if(!p)throw new Error('STOCK');detalles.push({producto:p._id,nombre:p.nombre,cantidad,precioUnitario:p.precioVenta,subtotal:p.precioVenta*cantidad});}const total=detalles.reduce((a,i)=>a+i.subtotal,0);[venta]=await Sale.create([{numero:`V-${Date.now()}-${Math.floor(Math.random()*1000)}`,caja:caja._id,cajero:req.usuario._id,items:detalles,total,metodoPago:req.body.metodoPago}],{session});caja.totalVentas+=total;caja.totalesPago[req.body.metodoPago]+=total;await caja.save({session});});res.status(201).json({mensaje:'Venta registrada',venta});}catch(e){const m={CAJA:'Debes abrir caja',PAGO:'Método de pago inválido',ITEMS:'Productos inválidos',STOCK:'Stock insuficiente'};res.status(m[e.message]?400:500).json({mensaje:m[e.message]||'Error al registrar venta'});}finally{await session.endSession();}};
const anular=async(req,res)=>{const motivo=req.body.motivo?.trim();if(!motivo)return res.status(400).json({mensaje:'El motivo de anulación es obligatorio'});const session=await mongoose.startSession();try{let resultado;await session.withTransaction(async()=>{const venta=await Sale.findOne({_id:req.params.id,estado:'COMPLETADA'}).session(session);if(!venta)throw new Error('VENTA');if(await require('../models/Delivery').exists({venta:venta._id,estado:{$nin:['CANCELADO']}}).session(session))throw new Error('DOMICILIO');for(const item of venta.items)await Product.updateOne({_id:item.producto},{$inc:{cantidadActual:item.cantidad}},{session});const caja=await Cash.findById(venta.caja).session(session);if(!caja)throw new Error('CAJA_NO_EXISTE');caja.totalVentas=Math.max(0,caja.totalVentas-venta.total);caja.totalesPago[venta.metodoPago]=Math.max(0,(caja.totalesPago[venta.metodoPago]||0)-venta.total);await caja.save({session});venta.estado='ANULADA';venta.anulacion={motivo,usuario:req.usuario._id,fecha:new Date()};resultado=await venta.save({session});});res.json({mensaje:'Venta anulada e inventario restaurado',venta:resultado});}catch(e){const m={VENTA:'Venta no encontrada o ya anulada',DOMICILIO:'Cancele primero el domicilio asociado',CAJA_NO_EXISTE:'La caja de la venta no existe'};res.status(m[e.message]?400:500).json({mensaje:m[e.message]||'No se pudo anular la venta'});}finally{await session.endSession();}};
module.exports={actual,abrir,cerrar,vender,historial,anular};
